
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:39 (enable_language)"
    message: |
      The target system is: Generic -  - arm
      The host system is: Windows - 10.0.26100 - 
  -
    kind: "message-v1"
    backtrace:
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:39 (enable_language)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: E:/MSYS2/install/mingw64/bin/arm-none-eabi-gcc.exe 
      Build flags: -mcpu=cortex-m4;-mfpu=fpv4-sp-d16;-mfloat-abi=hard;-mthumb;-mthumb-interwork;-Wall;-fdata-sections;-ffunction-sections;-finput-charset=UTF-8;-O0;-g3
      Id flags:  
      
      The output was:
      1
      E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/bin/ld.exe: E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\\libg.a(libc_a-exit.o): in function `exit':
      c:\\m\\b\\src\\newlib-4.4.0.20231231\\newlib\\libc\\stdlib/exit.c:65:(.text+0x14): undefined reference to `_exit'
      E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/bin/ld.exe: E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\\libg.a(libc_a-closer.o): in function `_close_r':
      c:\\m\\b\\src\\newlib-4.4.0.20231231\\newlib\\libc\\reent/closer.c:47:(.text+0xc): undefined reference to `_close'
      E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/bin/ld.exe: E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\\libg.a(libc_a-lseekr.o): in function `_lseek_r':
      c:\\m\\b\\src\\newlib-4.4.0.20231231\\newlib\\libc\\reent/lseekr.c:49:(.text+0x14): undefined reference to `_lseek'
      E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/bin/ld.exe: E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\\libg.a(libc_a-readr.o): in function `_read_r':
      c:\\m\\b\\src\\newlib-4.4.0.20231231\\newlib\\libc\\reent/readr.c:49:(.text+0x14): undefined reference to `_read'
      E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/bin/ld.exe: E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\\libg.a(libc_a-writer.o): in function `_write_r':
      c:\\m\\b\\src\\newlib-4.4.0.20231231\\newlib\\libc\\reent/writer.c:49:(.text+0x14): undefined reference to `_write'
      E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/bin/ld.exe: E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\\libg.a(libc_a-sbrkr.o): in function `_sbrk_r':
      c:\\m\\b\\src\\newlib-4.4.0.20231231\\newlib\\libc\\reent/sbrkr.c:51:(.text+0xc): undefined reference to `_sbrk'
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:39 (enable_language)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: E:/MSYS2/install/mingw64/bin/arm-none-eabi-gcc.exe 
      Build flags: -mcpu=cortex-m4;-mfpu=fpv4-sp-d16;-mfloat-abi=hard;-mthumb;-mthumb-interwork;-Wall;-fdata-sections;-ffunction-sections;-finput-charset=UTF-8;-O0;-g3
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        E:/Robot_Project/Basketball/General_Framework-fzh/CMakeFiles/3.30.1/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:39 (enable_language)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: E:/MSYS2/install/mingw64/bin/arm-none-eabi-g++.exe 
      Build flags: -mcpu=cortex-m4;-mfpu=fpv4-sp-d16;-mfloat-abi=hard;-mthumb;-mthumb-interwork;-Wall;-fdata-sections;-ffunction-sections;-finput-charset=UTF-8;-O0;-g3;-fno-rtti;-fno-exceptions;-fno-threadsafe-statics;-finput-charset=UTF-8
      Id flags:  
      
      The output was:
      1
      E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/bin/ld.exe: E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\\libg.a(libc_a-exit.o): in function `exit':
      c:\\m\\b\\src\\newlib-4.4.0.20231231\\newlib\\libc\\stdlib/exit.c:65:(.text+0x14): undefined reference to `_exit'
      E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/bin/ld.exe: E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\\libg.a(libc_a-closer.o): in function `_close_r':
      c:\\m\\b\\src\\newlib-4.4.0.20231231\\newlib\\libc\\reent/closer.c:47:(.text+0xc): undefined reference to `_close'
      E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/bin/ld.exe: E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\\libg.a(libc_a-lseekr.o): in function `_lseek_r':
      c:\\m\\b\\src\\newlib-4.4.0.20231231\\newlib\\libc\\reent/lseekr.c:49:(.text+0x14): undefined reference to `_lseek'
      E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/bin/ld.exe: E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\\libg.a(libc_a-readr.o): in function `_read_r':
      c:\\m\\b\\src\\newlib-4.4.0.20231231\\newlib\\libc\\reent/readr.c:49:(.text+0x14): undefined reference to `_read'
      E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/bin/ld.exe: E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\\libg.a(libc_a-writer.o): in function `_write_r':
      c:\\m\\b\\src\\newlib-4.4.0.20231231\\newlib\\libc\\reent/writer.c:49:(.text+0x14): undefined reference to `_write'
      E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/bin/ld.exe: E:/MSYS2/install/mingw64/bin/../lib/gcc/arm-none-eabi/13.3.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard\\libg.a(libc_a-sbrkr.o): in function `_sbrk_r':
      c:\\m\\b\\src\\newlib-4.4.0.20231231\\newlib\\libc\\reent/sbrkr.c:51:(.text+0xc): undefined reference to `_sbrk'
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:39 (enable_language)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: E:/MSYS2/install/mingw64/bin/arm-none-eabi-g++.exe 
      Build flags: -mcpu=cortex-m4;-mfpu=fpv4-sp-d16;-mfloat-abi=hard;-mthumb;-mthumb-interwork;-Wall;-fdata-sections;-ffunction-sections;-finput-charset=UTF-8;-O0;-g3;-fno-rtti;-fno-exceptions;-fno-threadsafe-statics;-finput-charset=UTF-8
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is GNU, found in:
        E:/Robot_Project/Basketball/General_Framework-fzh/CMakeFiles/3.30.1/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1192 (message)"
      - "E:/Cmake/share/cmake-3.30/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:39 (enable_language)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      arm-none-eabi-gcc.exe (GCC) 13.3.0
      Copyright (C) 2023 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...
